

[FIREBASE]
type = "service_account"
project_id = "login1-e7ab2"
private_key_id = "329db2144bd71e285141b20922e3a6201f125435"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDOAH7BC32/07CW
w25+v+AX29DqG+RYD5u3T7hzzUUDD3LN7XabMBE/q3eR5Qwz+2Vkzx76RzHrTVnB
kmaibmhFKE5xizE9MBXhGi4zZUGtsI8oTJOGAy1c+tw6MY1wAPrjAOojIVWSwvMl
XesfYnfmL52t4p/b9natuXoSVzI/ylt6nXvm0KKG3ReS8lHR/1S45nz1EIywVvPg
YONwvqDLSbysjNmpUzj9DVpbffzjoQzltWWiViIovYQnROkjxn/3qrryiDmGmCO7
gAwERWAOIzVuFlf07UtcWtHQ+v5xFMjHVqz/Vnki0NBKaTuNmDXvWfJlX6E3kjh+
shSA6nvPAgMBAAECggEAV3BDXRpNDmLCxkN+v6Me8dGWXABpzG0XmdfnQZQD8ngY
sUrVeKqO77kOwCj6JIhVMdRuYCpfCHLlIbJMCS8W6B/jJ/O+eyvRZaIwsRUOKzTR
lvfl+FCZ7Sj32GWXFM79ruQA/ddU1L4V6arzNXecz+IvKhMS6pEzL6sWIvnK9OLj
OvahkTu7pxmHqIMH16ZFGoV+MXZTO9alM0gLNiyHXfKHt/oPmuS4SMy5crMBeaSs
WTw9/b+tBKW2wjtAZ+eygmr7O0sPzBR0xG6EZy6fo4QpACKijHideouo7/k+2uvY
6A9m9Y3rhNaqe3c8RGHxvP94GGZsmUt7amSCa8mLIQKBgQDnzVaJRUHd1xvF2+G1
g06Lirn1CLdS/NjWNcR6S52a4neZF3e61TzY/+XXJyPbLIEQ5R0D/u2wRHyTORTa
oKH467npTyjgDX8Gb5fgD9KIQMkD52OT6YhFQ+xQ/gp3pHG6TGb02Z1I80vZOUiR
ZTJ8yogDctUAJRJ96v+4XWHEbwKBgQDjgazkVx9Srb9L+zlWzk4pSsoO/5K2tzKp
VFUFDrtO7frg4U6a7wx5xTzhFVfxxZJwr5wChJFXAKbJBKk0ykCIVX/D5oElZu3q
71xMm/xugtydrzZqUzZK0PAoV5CJtLeGd7shKCGMObblkjM0zVaBVW/Op+bWSSF/
vozpIf4uoQKBgDqanms8GEf2z225hpn2ZZA/9X2uw3J2vHeDxnXI0kLLSMNqvHl+
2dBe+gPoQFd0K/lSg4B0HjG3TuuFvfD8NZcSOcFzovjqUJgW9IXQWkDaaDfVc0Z8
/1fLsV5Uq97Ns3cPQ+RZdDtyT1XO9rrTo+0K41JD4PgVZ1RwalB5Q3N/AoGAFkI9
tCmB+wjcyoZN2dxdcVTL6CPBKvdJkZ+aoeALG3HVNeNVWXtB8TgG+M6pyBHYfgXw
cZ6eybBaoRg/pdaT8cLLuVL4F7y2UmIQ2b35OKa9BwB5hnWVvkQq+wd2MMLpodJd
EKVogtuytUtUjzn32LePNNzgjN6i1GjESJr2z4ECgYEApIeIh3kpfrtMqRpasdtA
7WZwVswvciCzEOGRRld7Q1h+pRXNdhcVcB7N+WDIiTHdc9q1iBpdCq733KvK4U57
pflKVRMj9BikZQKw638M9zWCWAo9zGmMZc+msGVThJenLpC3Sh/3+q691su1mC62
tj2DGo7gJ8WnGYEzMVJcdQ0=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@login1-e7ab2.iam.gserviceaccount.com"
client_id = "113780619554387369019"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40login1-e7ab2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
web_api_key = "AIzaSyCj0UPv444P-C6ggFZ8Q_NXvSSBraHeDG4"
